# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/' # Location of package manifests
    schedule:
      interval: daily
    assignees:
      - 'mia-riezebos'
    allow:
      - dependency-type: all
    commit-message:
      include: scope
      prefix: '[gha] '
    labels:
      - github-actions
      - dependencies
    reviewers:
      - 'mia-riezebos'
    versioning-strategy: increase-if-necessary

  - package-ecosystem: npm # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
        day: saturday
        interval: weekly
        time: '10:00'
        timezone: Europe/Amsterdam
    assignees:
      - 'mia-riezebos'
    allow:
      - dependency-type: all
    commit-message:
      include: scope
      prefix: '[dep|pnpm] '
    labels:
      - pnpm
      - dependencies
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '/'
    reviewers:
      - 'mia-riezebos'
    versioning-strategy: increase-if-necessary
    groups:
      breaking-security-updates:
        applies-to: security-updates
        update-types:
          - major
      security-updates:
        applies-to: security-updates
        update-types:
          - minor
          - patch
      breaking-version-updates:
        applies-to: version-updates
        update-types:
          - major
      version-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
