name: Automatic Publish of Stable Releases

on:
    release:
        types:
            - published

jobs:
    stable-release:
        name: Stable Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Make stable release to npm
              uses: esamatti/npm-release@v2
              with:
                  type: stable
                  token: ${{ secrets.NPM_TOKEN }}
