name: Automatic Release

on:
    push:
        branches:
            - main

jobs:
    github:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Automatic GitHub Release
              uses: justincy/github-action-npm-release@2.0.1
              id: release
            - name: Print release output
              if: ${{ steps.release.outputs.released == 'true' }}
              run: echo Release ID ${{ steps.release.outputs.release_id }}
    prerelease:
        name: Prerelease
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Make prerelease to npm
              uses: epeli/npm-release@v1
              with:
                  type: prerelease
                  token: ${{ secrets.NPM_TOKEN }}
